### ISSUE TITLE
Rewrite the CSS file to have prefixes within the syntax

### ISSUE THREAD

**Issue by ghost** [cobwebdev/cssheet#8]
In order to help not conflict with other CSS frameworks we are implementing a prefix at the front of our syntax in order for CSSheet CSS classes to be more recognisable, along with this we are no-longer going to condense CSS classes. A good example of our aim is [W3.CSS](https://www.w3schools.com/w3css/defaulT.asp)

Our prefix will be: `cs`
then the main clauses for the framework shall be written in full.

Example
`bg-red1` will be reformatted into `cs-background-red-1`, 
this should aide with readability for the framework.

**Comment by TheOceanBreeze** [comment]
I'll look into doing this once we resolve the pull request.
