### ISSUE TITLE
Add more themes to CSSheet

### ISSUE THREAD

**Issue by ghost** [cobwebdev/cssheet#9]
For CSSheet beta we are hoping to add more themes to CSSheet. 
A full theme should include; Background colours, foreground colours, button styling, borders and more. **Please refer to the CSS to check what needs to be added for themes.**

Some theme ideas include:
- A modern webpage theme
- A more retro-styled webpage theme
- A one-page webpage theme
- A multi-page webpage theme
- An image-heavy page theme.

**Comment by TheOceanBreeze** [comment]
Got rid of themes... Will not be implementing.
